### ISSUE TITLE
Future proofing

### ISSUE THREAD

**Issue by tobyink** [bayashi/Duadua#96]
You should allow:

```perl
my $h = HTTP::Headers->new(
  User_Agent => 'Blah/1.0',
  Some_Other_Header => 'foo',
);
my $d = Duadua->new( $h );
```

As an alternative to just passing a string to the constructor.

This is because it's likely in the next year or two, the `Sec-CH-*` headers are going to become more important than the `User-Agent` header when it comes to detecting the browser and its features.

**Comment by bayashi** [comment]
Thanks for the nice suggestion!
